version: "3.7"

services:
  fastapi:
    container_name: api_todo_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app/"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tokyo
      - LC_CTYPE=C.UTF-8
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ./app/core/envs/.env.${STAGE}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  postgres_data:
