"""mod columns

Revision ID: 8b2dd8570c90
Revises: d9e5e65f5d9a
Create Date: 2024-04-20 18:03:36.014037+09:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b2dd8570c90"
down_revision = "d9e5e65f5d9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.drop_constraint("users_login_id_key", "users", type_="unique")
    op.drop_column("users", "login_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "login_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("users_login_id_key", "users", ["login_id"])
    op.drop_index(op.f("ix_users_id"), table_name="users")
    # ### end Alembic commands ###
