"""Change id type to UUID

Revision ID: b74692ad8b3d
Revises: 8b2dd8570c90
Create Date: 2024-04-20 18:20:37.994227+09:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b74692ad8b3d"
down_revision = "8b2dd8570c90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
