"""add user_id

Revision ID: d6b7efc36e7b
Revises: b74692ad8b3d
Create Date: 2024-04-20 18:29:39.416316+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6b7efc36e7b'
down_revision = 'b74692ad8b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_index('ix_users_id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_users_id', 'users', ['id'], unique=True)
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
